# Support Vector Machines
You should build a machine learning pipeline using a support vector machine model. In particular, you should do the following:
- Load the `mnist` dataset using [Pandas](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html). You can find this dataset in the datasets folder.
- Split the dataset into training and test sets using [Scikit-Learn](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html). 
- Train and test a support vector machine model using [Scikit-Learn](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html).
- Check the documentation to identify the most important hyperparameters, attributes, and methods of the model. Use them in practice.

In [43]:
import pandas as pd 
df = pd.read_csv("mnist.csv")
print(df)
df.head
df.shape

         id  class  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0     31953      5       0       0       0       0       0       0       0   
1     34452      8       0       0       0       0       0       0       0   
2     60897      5       0       0       0       0       0       0       0   
3     36953      0       0       0       0       0       0       0       0   
4      1981      3       0       0       0       0       0       0       0   
...     ...    ...     ...     ...     ...     ...     ...     ...     ...   
3995  25268      1       0       0       0       0       0       0       0   
3996   6473      6       0       0       0       0       0       0       0   
3997   5821      7       0       0       0       0       0       0       0   
3998   1751      9       0       0       0       0       0       0       0   
3999  56752      2       0       0       0       0       0       0       0   

      pixel8  ...  pixel775  pixel776  pixel777  pixel778  pixe

(4000, 786)

In [61]:
X=df.drop(columns="class",axis=1)
y=df["class"]

In [62]:
from sklearn.model_selection import train_test_split
import numpy as np
X_train, X_test,y_train,y_test = train_test_split(X,y ,
                                   random_state=0, 
                                   test_size=0.2, 
                                   shuffle=True)

print('X_train : ')
print(X_train.head())
print('')
print('X_test : ')
print(X_test.head())
print('')
print('y_train : ')
print(y_train.head())
print('')
print('y_test : ')
print(y_test.head())


X_train : 
         id  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
1161  28481       0       0       0       0       0       0       0       0   
2355  27614       0       0       0       0       0       0       0       0   
1831  52154       0       0       0       0       0       0       0       0   
156   54120       0       0       0       0       0       0       0       0   
195   32839       0       0       0       0       0       0       0       0   

      pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
1161       0  ...         0         0         0         0         0         0   
2355       0  ...         0         0         0         0         0         0   
1831       0  ...         0         0         0         0         0         0   
156        0  ...         0         0         0         0         0         0   
195        0  ...         0         0         0         0         0         0   

      pixel781  pixel782  p

In [63]:
from sklearn import svm
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC()
clf.fit(X, y)
clf.predict([[2., 2.]])


array([1])

In [64]:
clf.support_vectors_
clf.support_
clf.n_support_

array([1, 1], dtype=int32)

In [65]:
X = [[0], [1], [2], [3]]
Y = [0, 1, 2, 3]
clf = svm.SVC(decision_function_shape='ovo')
clf.fit(X, Y)

SVC(decision_function_shape='ovo')

#Regression fit in SVM

In [49]:
from sklearn import svm
X = [[0, 0], [2, 2]]
y = [0.5, 2.5]
regr = svm.SVR()
regr.fit(X, y)
regr.predict([[1, 1]])


array([1.5])

In [50]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

clf = make_pipeline(StandardScaler(), SVC())

#Kernel Functions


In [55]:
linear_svc = svm.SVC(kernel='linear')
linear_svc.kernel
rbf_svc = svm.SVC(kernel='rbf')
rbf_svc.kernel


'rbf'

#Using Gram Matrix


In [56]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn import svm
X, y = make_classification(n_samples=10, random_state=0)
X_train , X_test , y_train, y_test = train_test_split(X, y, random_state=0)
clf = svm.SVC(kernel='precomputed')
# linear kernel computation
gram_train = np.dot(X_train, X_train.T)
clf.fit(gram_train, y_train)
SVC(kernel='precomputed')
# predict on training examples
gram_test = np.dot(X_test, X_train.T)
clf.predict(gram_test)


array([0, 1, 0])